# Generated by Django 5.1.1 on 2024-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DengueCases',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('week', models.IntegerField()),
                ('cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
