# Generated by Django 5.1.1 on 2024-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('chatgpt_summarization', models.TextField()),
            ],
        ),
    ]
