# Generated by Django 5.1.1 on 2024-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default='Null'),
            preserve_default=False,
        ),
    ]
