import NewsCard from './NewsCard';
import { useState, useEffect } from "react";
import { ColorRing } from 'react-loader-spinner';

export default function NewsSection({handleTabChange}) {
    const [news, setNews] = useState([]);

    useEffect(() => {
        fetch('https://dengue-watch-backend-f59b9593b035.herokuapp.com/news/')
            .then(response => response.json())
            .then(data => {
                console.log(data);  // Debugging purposes
                setNews(data);
            });
    }, []);
    useEffect(() => {
    handleTabChange("News");
    }, [handleTabChange]);

    return (
        <div className="py-4 px-4 flex flex-col items-center">
            <h1 className="text-4xl font-bold text-center mb-8">News</h1>
            <h4 className="text-xl font-semibold text-center mb-4">Latest news articles related to dengue fever</h4>
            {news.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 justify-center">
                    {news.map((newsItem) => (
                        <NewsCard
                            key={newsItem.id}
                            title={newsItem.title}
                            summary={newsItem.chatgpt_summ_web}
                            link={newsItem.url}
                            image={newsItem.img_url}
                            pub_date={newsItem.published_date}
                            description={newsItem.description}
                            source={newsItem.source}
                        />
                    ))}
                </div>
            ) : (
                <div className="flex justify-center items-center h-64 w-full">
                    <ColorRing color={"#800080"} />
                </div>
            )}
            
            <p className="text-gray-500 text-center mt-4">This content is generated by Chat-GPT 4. Results may not be accurate.</p>
        </div>
    );
}
