import NewsCard from './NewsCard';
import { useState, useEffect } from "react";

export default function NewsSection() {
    const [news, setNews] = useState([]);
    const date = getDateNow();

    useEffect(() => {
        fetch('https://dengue-watch-backend-f59b9593b035.herokuapp.com/news/?date=' + date)
            .then(response => response.json())
            .then(data => {
                console.log(data);  // Debugging purposes
                setNews(data);
            });
    }, [date]);

    return (
        <div className="bg-gradient-to-r from-blue-100 to-blue-300 shadow-lg py-4 flex flex-col items-center">
            <h1 className="text-2xl font-bold text-center">Top Stories</h1>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 justify-center">
                {news.map((newsItem) => (
                    <NewsCard
                        key={newsItem.id}
                        title={newsItem.title}
                        summary={newsItem.chatgpt_summ_web}
                        link={newsItem.url}
                        image={newsItem.img_url}
                        pub_date={newsItem.published_date}
                        description={newsItem.description}
                        source={newsItem.source}
                    />
                ))}
            </div>
            <p className="text-gray-500 text-center mt-4">This content is generated by Chat-GPT 4. Results may not be accurate.</p>
        </div>
    );
}

const getDateNow = () => {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0'); // getMonth() returns 0-based month
    const day = String(now.getDate()).padStart(2, '0');

    const formattedDate = `${year}-${month}-${day}`;
    return formattedDate;
}
